### ISSUE TITLE
Version 1.0.66 crashes with System.Transactions.TransactionAbortedException

### ISSUE THREAD

**Issue by iwhp** [madskristensen/WorkspaceFiles#36]
**Describe the bug**
When I open some projects they crash, some do not

**To Reproduce**
1. Start Visual Studio
2. Open a project (not with all)
3. A window "Preparing Solution..." is shown and it takes 5-10 minutes. Then in Solution Explorer an exception is shown.

**Expected behavior**
Open the solution in Solution explorer

**Exception**
Failed to create view with exception:
```
System.Transactions.TransactionAbortedException: 

The transaction has aborted. ---> System.TimeoutException: Transaction Timeout
   --- End of inner exception stack trace ---
   at System.Transactions.TransactionStateAborted.BeginCommit(InternalTransaction tx, Boolean asyncCommit, AsyncCallback asyncCallback, Object asyncState)
   at System.Transactions.CommittableTransaction.Commit()
   at System.Transactions.TransactionScope.InternalDispose()
   at System.Transactions.TransactionScope.Dispose()
   at Microsoft.VisualStudio.GraphModel.GraphTransactionScope.Dispose()
   at Microsoft.VisualStudio.PlatformUI.AttachedCollectionService.EndBatchInitializationScope()
   at Microsoft.VisualStudio.PlatformUI.AttachedCollectionService.BatchInitializationScope.DisposeManagedResources()
   at Microsoft.VisualStudio.PlatformUI.DisposableObject.Dispose(Boolean disposing)
   at Microsoft.VisualStudio.PlatformUI.DisposableObject.Dispose()
   at Microsoft.VisualStudio.PlatformUI.SolutionNavigatorPane.RefillNavigator(Boolean skipRestorePhase, Boolean isFirstLoad)
```

**Comment by madskristensen** [comment]
I cannot reproduce this error. Can you share the solution you are opening, by chance?

**Comment by iwhp** [comment]
I do have a similar issue.
Smaller solutions can be opened without issues.
Bigger solutions, which also contain npm folder (node_modules) with many npm packages, cannot be opened.

**Comment by madskristensen** [comment]
Do you have a repro project you can share?

**Comment by madskristensen** [comment]
Should I filter out `node_modules`?
